EryazProje/EryazProje/Controllers/KategorilerController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EryazProje.Models;

namespace EryazProje.Controllers
{

    public class KategorilerController : Controller
    {
        SqlConnection baglanti = new SqlConnection(ConfigurationManager.ConnectionStrings["Baglanti"].ConnectionString);

        // GET: Kategoriler
        public ActionResult Index()
        {
            return View();
            
        }
        public JsonResult GetKategoriList()
        {
            SqlCommand komut = new SqlCommand();
            komut.CommandText = "KategoriListele";
            komut.Connection = baglanti;
            baglanti.Open();
            SqlDataReader rdr = komut.ExecuteReader();
            List<Kategoriler> liste = new List<Kategoriler>();
            while (rdr.Read())
            {
                liste.Add(new Kategoriler()
                {
                    KategoriId=rdr.GetInt32(0),
                    KategoriAdi = rdr.GetString(1)
                });
            }
            baglanti.Close();
            return Json(liste,JsonRequestBehavior.AllowGet);
        }

        //public ActionResult YeniGoster(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    return PartialView("_PartialKategoriEkle");
        //}
        [HttpPost]
        public ActionResult KategoriEkle(Kategoriler model)
        {
            SqlCommand komut = new SqlCommand("KategoriEkle", baglanti); //store procedure
            komut.CommandType = CommandType.StoredProcedure; //sen prosedür çalıştıracaksın demek.

            komut.Parameters.AddWithValue("@KategoriAdi", model.KategoriAdi);

            baglanti.Open();
            komut.ExecuteNonQuery();
            baglanti.Close();
            return RedirectToAction("Index");

        }
        public ActionResult KategoriDuzenle(Kategoriler model)
        {
            SqlCommand komut = new SqlCommand("KategoriDuzenle", baglanti); //store procedure
            komut.CommandType = CommandType.StoredProcedure; //sen prosedür çalıştıracaksın demek.

            komut.Parameters.AddWithValue("@KategoriId", model.KategoriId);
            komut.Parameters.AddWithValue("@KategoriAdi", model.KategoriAdi);
            

            baglanti.Open();
            komut.ExecuteNonQuery();
            baglanti.Close();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriSil(Kategoriler model)
        {
            SqlCommand komut = new SqlCommand("KategoriSil", baglanti); //store procedure
            komut.CommandType = CommandType.StoredProcedure; //sen prosedür çalıştıracaksın demek.

            komut.Parameters.AddWithValue("@KategoriId", model.KategoriId);

            baglanti.Open();
            komut.ExecuteNonQuery();
            baglanti.Close();
            return RedirectToAction("Index");
        }

        public JsonResult GetEditDeleteKategori(int KategoriId)
        {
            SqlCommand komut = new SqlCommand();
            komut.CommandText = "select * from Kategoriler where KategoriId=@KategoriId";
            komut.Parameters.AddWithValue("@KategoriId", KategoriId);
            komut.Connection = baglanti;
            baglanti.Open();
            SqlDataReader rdr = komut.ExecuteReader();
            Kategoriler k = new Kategoriler();
            while (rdr.Read())
            {
                k.KategoriId = rdr.GetInt32(0);
                k.KategoriAdi = rdr.GetString(1);
            }
            baglanti.Close();
            return Json(k, JsonRequestBehavior.AllowGet);

            //SqlCommand komut = new SqlCommand();
            //komut.CommandText = "select KategoriAdi from Kategoriler where KategoriId=@KategoriId";
            //komut.Parameters.AddWithValue("@KategoriId", KategoriId);

            //komut.Connection = baglanti;
            //baglanti.Open();
            //string kategoriadi=(string)komut.ExecuteScalar();
            //baglanti.Close();
            //return Json(kategoriadi, JsonRequestBehavior.AllowGet);
        }
    }
}

EryazProje/EryazProje/Controllers/UrunlerController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using EryazProje.Models;

namespace EryazProje.Controllers
{
    public class UrunlerController : Controller
    {
        SqlConnection baglanti = new SqlConnection(ConfigurationManager.ConnectionStrings["Baglanti"].ConnectionString);

        // GET: Urunler
        public ActionResult Index()
        {
            //List<Urunler> urunler = new List<Urunler>();
            //var model =urunler.ToList();
            //if (!string.IsNullOrEmpty(ara))
            //{
            //    model = model.Where(x => x.UrunAdi.Contains(ara)).ToList();
            //}
            return View();
        }
        public JsonResult GetUrunList()
        {
            //SqlCommand komut = new SqlCommand("select UrunId, UrunAdi,UrunAciklamasi,UrunFiyati,KategoriId from Urunler", baglanti);
            SqlCommand komut = new SqlCommand("UrunListele", baglanti); //store procedure

            baglanti.Open();
            SqlDataReader rdr = komut.ExecuteReader();

            List<UrunlerveKategoriler> liste = new List<UrunlerveKategoriler>();  //bak unutma eski hali
            while (rdr.Read())
            {
                liste.Add(new UrunlerveKategoriler()
                {
                    UrunId = rdr.GetInt32(0),
                    UrunAdi = rdr.GetString(1),
                    UrunAciklamasi = rdr.IsDBNull(2) ? string.Empty : rdr.GetString(2),
                    UrunFiyati = rdr.GetDecimal(3),
                    KategoriId = rdr.GetInt32(4)

                });
            }
            baglanti.Close();
            return Json(liste, JsonRequestBehavior.AllowGet);
        }
        
        //public ActionResult YeniGoster()
        //{
        //    return PartialView("_PartialUrunEkle");
        //}
        public ActionResult UrunEkle(UrunlerveKategoriler model)
        {
            SqlCommand komut2 = new SqlCommand("select KategoriAdi from Kategoriler", baglanti);
            baglanti.Open();
            SqlDataReader rdr = komut2.ExecuteReader();
            
            List<Kategoriler> liste = new List<Kategoriler>();  //bak unutma eski hali
            while (rdr.Read())
            {
                
                liste.Add(new Kategoriler()
                {
                    KategoriAdi = rdr.GetString(1),
                    KategoriId = rdr.GetInt32(0)
                });
            }
            ViewBag.liste2 = new SelectList(liste, "ID", "Title", model.KategoriId);
            baglanti.Close();
           // ViewBag.liste = liste.ToList();


            SqlCommand komut = new SqlCommand("UrunEkle", baglanti); //store procedure
            komut.CommandType = CommandType.StoredProcedure; //sen prosedür çalıştıracaksın demek.

            komut.Parameters.AddWithValue("@UrunId", model.UrunId);
            komut.Parameters.AddWithValue("@UrunAdi", model.UrunAdi);
            komut.Parameters.AddWithValue("@UrunAciklamasi", model.UrunAciklamasi);
            komut.Parameters.AddWithValue("@UrunFiyati", model.UrunFiyati);
            komut.Parameters.AddWithValue("@KategoriId", model.KategoriId);
            
            baglanti.Open();
            komut.ExecuteNonQuery();
            baglanti.Close();
            return RedirectToAction("Index");

        }
        public ActionResult UrunDuzenle(UrunlerveKategoriler model)
        {
            SqlCommand komut2 = new SqlCommand("select * from Kategoriler", baglanti);
            baglanti.Open();
            SqlDataReader rdr = komut2.ExecuteReader();
            List<Kategoriler> liste = new List<Kategoriler>();  //bak unutma eski hali
            while (rdr.Read())
            {

                liste.Add(new Kategoriler()
                {
                    KategoriAdi = rdr.GetString(1),
                    KategoriId = rdr.GetInt32(0)
                });
            }
            ViewBag.liste2 = new SelectList(liste, "ID", "Title", model.KategoriId);
            baglanti.Close();


            SqlCommand komut = new SqlCommand("UrunDuzenle", baglanti); //store procedure
            komut.CommandType = CommandType.StoredProcedure; //sen prosedür çalıştıracaksın demek.

            komut.Parameters.AddWithValue("@UrunId", model.UrunId);
            komut.Parameters.AddWithValue("@UrunAdi", model.UrunAdi);
            komut.Parameters.AddWithValue("@UrunAciklamasi", model.UrunAciklamasi);
            komut.Parameters.AddWithValue("@UrunFiyati", model.UrunFiyati);
            komut.Parameters.AddWithValue("@KategoriId", model.KategoriId);

            baglanti.Open();
            komut.ExecuteNonQuery();
            baglanti.Close();
            return RedirectToAction("Index");
        }
        public ActionResult UrunSil(UrunlerveKategoriler model)
        {
            SqlCommand komut2 = new SqlCommand("select * from Kategoriler", baglanti);
            baglanti.Open();
            SqlDataReader rdr = komut2.ExecuteReader();
            List<Kategoriler> liste = new List<Kategoriler>();  //bak unutma eski hali
            while (rdr.Read())
            {

                liste.Add(new Kategoriler()
                {
                    KategoriAdi = rdr.GetString(1),
                    KategoriId = rdr.GetInt32(0)
                });
            }
            ViewBag.liste2 = new SelectList(liste, "ID", "Title", model.KategoriId);
            baglanti.Close();


            SqlCommand komut = new SqlCommand("UrunSil", baglanti); //store procedure
            komut.CommandType = CommandType.StoredProcedure; //sen prosedür çalıştıracaksın demek.

            komut.Parameters.AddWithValue("@UrunId", model.UrunId);

            baglanti.Open();
            komut.ExecuteNonQuery();
            baglanti.Close();
            return RedirectToAction("Index");
        }

        public JsonResult GetEditDeleteUrun(int UrunId)
        {
            SqlCommand komut = new SqlCommand();
            komut.CommandText = "select * from Urunler where UrunId=@UrunId";
            komut.Parameters.AddWithValue("@UrunId", UrunId);
            komut.Connection = baglanti;
            baglanti.Open();
            SqlDataReader rdr = komut.ExecuteReader();
            Urunler u = new Urunler();
            while (rdr.Read())
            {
                u.UrunId = rdr.GetInt32(0);
                u.UrunAdi = rdr.GetString(1);
                u.UrunAciklamasi = rdr.IsDBNull(2) ? string.Empty : rdr.GetString(2);
                u.UrunFiyati = rdr.GetDecimal(3);
                u.KategoriId = rdr.GetInt32(4);
            }
            baglanti.Close();
            return Json(u, JsonRequestBehavior.AllowGet);

            
        }
    }
}

EryazProje/EryazProje/Views/Shared/_Layout.cshtml
@using EryazProje.Models

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@ViewBag.Title</title>

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/shop-homepage.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

</head>

<body>
    @{ 
        Kullanicilar user = null;
        if (Session["login"] != null)
        {
            user = (Kullanicilar)Session["login"];
        } 
    }

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/Home/Index">Ana Sayfa</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    @if (user != null)
                    {
                        <li>
                            <a href="/Kategoriler/Index">
                                <span class="glyphicon glyphicon-th-list"></span> Kategoriler
                            </a>
                        </li>
                        <li>
                            <a href="/Urunler/Index">
                                <span class="glyphicon glyphicon-th-list"></span> Ürünler
                            </a>
                        </li>
                    }

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (user == null)
                    {
                        <li>
                            <a href="/Home/Login">
                                <span class="glyphicon glyphicon-log-in"></span> Giriş
                            </a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="#">
                                <span class="glyphicon glyphicon-user"></span> Betül Erkal
                            </a>
                        </li>
                        <li>
                            <a href="/Home/Logout">
                                <span class="glyphicon glyphicon-log-out"></span> Çıkış
                            </a>
                        </li>
                    }

                </ul>

            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    @RenderSection("footer", required: false)     @*bazı sayfalarda görünecek bazılarında görünmeyecek*@



</body>

</html>

EryazProje/EryazProje/Views/Shared/_PartialFooter.cshtml
<div class="container">
    <hr>
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-4 text-right">
                <br /><br />
                <p>Tüm Hakları Saklıdır &copy; @DateTime.Now.Year</p>
            </div>
            
        </div>
    </footer>

</div>

EryazProje/EryazProje/Views/Shared/_PartialKategoriDuzenle.cshtml
@model EryazProje.Models.Kategoriler

@using (Html.BeginForm("KategoriDuzenle", "Kategoriler", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="modal" id="myModal" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3>Kategori Düzenle</h3>
                        <button class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        @Html.HiddenFor(model => model.KategoriId)
                        <div class="form-group">
                            @Html.LabelFor(model => model.KategoriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group container">
                            <div style="float:left">
                                <button type="submit" class="btn btn-success">
                                    <span class="glyphicon glyphicon-floppy-saved"></span>
                                    Kaydet
                                </button>
                            </div>
                            <div style="float:right">
                                <button class="btn btn-dark" data-dismiss="modal">
                                    <span class="glyphicon glyphicon-floppy-saved"></span>
                                    Kapat
                                </button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

}





@*<div class="col-md-4">
    <h3>Kategori Düzenle</h3>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.KategoriId)

            <div class="form-group">
                @Html.LabelFor(model => model.KategoriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-floppy-saved"></span>
                        Kaydet
                    </button>

                </div>
            </div>
        </div>
    }
</div>
<link href="~/Content/validation-summary.css" rel="stylesheet" />*@

EryazProje/EryazProje/Views/Shared/_PartialKategoriEkle.cshtml
@model EryazProje.Models.Kategoriler

@using (Html.BeginForm("KategoriEkle", "Kategoriler", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="modal" id="ModalEkle" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3>Kategori Ekle</h3>
                        <button class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            @Html.LabelFor(model => model.KategoriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group container">
                            <div style="float:left">
                                <button type="submit" class="btn btn-success">
                                    <span class="glyphicon glyphicon-floppy-saved"></span>
                                    Kaydet
                                </button>
                            </div>
                            <div style="float:right">
                                <button class="btn btn-dark" data-dismiss="modal">
                                    <span class="glyphicon glyphicon-floppy-saved"></span>
                                    Kapat
                                </button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

}







@*var notid = -1;
    $(function () {
        $('#ModalEkle').on('show.bs.modal', function (e) {
            notid = $(e.relatedTarget).data("notid");   //related target butonu yakalamak için
            $("#modal-body").load("/Kategoriler/YeniGoster/" + notid);
        })
    })
    function kategoriislem(btn, islem, spanid) {
        var mode = $(btn).data("create-mode")
        if (islem == "insertislem") {
            $.ajax({
                method: "POST",
                url: "/Kategoriler/KategoriEkle/"
            }).done(function (data) {
                if (data.sonuc) {   //ekleme gerçekleştiyse yorumlar tekrar yüklenir
                    $("#modal-body").load("/Kategoriler/YeniGoster/" + notid);
                }
                else {
                    alert("Kategori eklenemedi.")
                }
            }).fail(function () {
                alert("Sunucu ile bağlantı kurulamadı.")
            })
        }
        //else if (islem == "deleteislem") {
        //    var mesaj = confirm("Yorum silinsin mi?")
        //    if (!mesaj) {
        //        return false;
        //    }
        //    $.ajax({
        //        method: "GET",
        //        url: "/Comment/Delete/" + yorumid
        //    }).done(function (data) {
        //        if (data.sonuc) {   //silme gerçekleştiyse yorumlar tekrar yüklenir
        //            $("#modal-body").load("/Comment/YorumGoster/" + notid);
        //        }
        //        else {
        //            alert("Yorum silinemedi.")
        //        }
        //    }).fail(function () {
        //        alert("Sunucu ile bağlantı kurulamadı.")
        //    })
        //}
        //else if (islem == "insertislem") {
        //    var txt = $("#yorum_text").val();
        //    $.ajax({
        //        method: "POST",
        //        url: "/Comment/Create/",
        //        data: { "text": txt, "notid": notid }
        //    }).done(function (data) {
        //        if (data.sonuc) {   //ekleme gerçekleştiyse yorumlar tekrar yüklenir
        //            $("#modal-body").load("/Comment/YorumGoster/" + notid);
        //        }
        //        else {
        //            alert("Yorum eklenemedi.")
        //        }
        //    }).fail(function () {
        //        alert("Sunucu ile bağlantı kurulamadı.")
        //    })
        //}
    }*@

@*<div class="col-md-4">
        <h3>Kategori Ekle</h3>
        <hr />
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                <hr />
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.KategoriAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.KategoriAdi, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-floppy-saved"></span>
                            Kaydet
                        </button>

                    </div>
                </div>

            </div>
        }
    </div>
    <link href="~/Content/validation-summary.css" rel="stylesheet" />*@

EryazProje/EryazProje/Views/Shared/_PartialKategoriSil.cshtml
@model EryazProje.Models.Kategoriler

<div class="col-md-4">
    <h3>Kategori Sil</h3>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <hr />
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.KategoriAdi)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.KategoriAdi)
                </dd>

            </dl>
        </div>
        <div class="col-md-12">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <button type="submit" class="btn btn-danger">
                        <span class="glyphicon glyphicon-floppy-remove"></span>
                        Sil
                    </button>

                </div>
            }
        </div>
    </div>
</div>

EryazProje/EryazProje/Views/Shared/_PartialUrunDuzenle.cshtml
@model EryazProje.Models.UrunlerveKategoriler

@using (Html.BeginForm("UrunDuzenle", "Urunler", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="modal" id="myModal" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3>Ürün Düzenle</h3>
                        <button class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        @Html.HiddenFor(model => model.UrunId)

                        <div class="form-group">
                            @Html.LabelFor(model => model.UrunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.UrunAciklamasi, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UrunAciklamasi, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.UrunFiyati, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.UrunFiyati, new { htmlAttributes = new { @class = "form-control" } })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.KategoriId, "KategoriId", htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <div class="form-group container">
                            <div style="float:left">
                                <button type="submit" class="btn btn-success">
                                    <span class="glyphicon glyphicon-floppy-saved"></span>
                                    Kaydet
                                </button>
                            </div>
                            <div style="float:right">
                                <button class="btn btn-dark" data-dismiss="modal">
                                    <span class="glyphicon glyphicon-floppy-saved"></span>
                                    Kapat
                                </button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

}










@*<div class="col-md-4">
    <h3>Ürün Düzenle</h3>
    <hr />
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Urunler</h4>
            <hr />
            @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.UrunId)

            <div class="form-group">
                @Html.LabelFor(model => model.UrunAdi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UrunAdi, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UrunAciklamasi, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UrunAciklamasi, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UrunFiyati, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UrunFiyati, new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.KategoriId, "KategoriId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon-floppy-saved"></span>
                        Kaydet
                    </button>

                </div>
            </div>
        </div>
    }

</div>
<link href="~/Content/validation-summary.css" rel="stylesheet" />*@